(require 'ert)
(require 'jcalendar)

(ert-deftest jcalendar-era ()
  ""
  :tags '(jcalendar)
  (should (equal (car (jcalendar--date-to-era '(1 6 1989))) "昭和"))
  (should (equal (car (jcalendar--date-to-era '(1 7 1989))) "昭和"))
  (should (equal (car (jcalendar--date-to-era '(1 8 1989))) "平成"))
  (should (equal (car (jcalendar--date-to-era '(1 25 1868))) "明治"))
  (should-error (jcalendar--date-to-era '(1 24 1868)) :type 'args-out-of-range))

(ert-deftest jcalendar-leap ()
  ""
  :tags '(jcalendar)
  (should (equal (jcalendar--qreki '(3 1 2014)) '(2 1 nil nil)))
  (should (equal (jcalendar--qreki '(1 31 2014)) '(1 1 nil nil)))
  (should (equal (jcalendar--qreki '(5 20 2012)) '(3 30 nil t)))
  (should (equal (jcalendar--qreki '(5 21 2012)) '(4 1 nil nil)))
  (should (equal (jcalendar--qreki '(4 20 2012)) '(3 30 nil nil)))
  (should (equal (jcalendar--qreki '(4 21 2012)) '(3 1 nil t))))

(ert-deftest jcalendar-kansuji ()
  ""
  :tags '(jcalendar)
  (should (equal (jcalendar-number-to-kanji 0) "零"))
  (should (equal (jcalendar-number-to-kanji 1) "一"))
  (should (equal (jcalendar-number-to-kanji 12) "十二"))
  (should (equal (jcalendar-number-to-kanji 123) "百二十三"))
  (should (equal (jcalendar-number-to-kanji 1234) "千二百三十四"))
  (should (equal (jcalendar-number-to-kanji 12345) "一万二千三百四十五"))
  (should (equal (jcalendar-number-to-kanji 123456) "十二万三千四百五十六"))
  (should (equal (jcalendar-number-to-kanji 1234567) "百二十三万四千五百六十七"))
  (should (equal (jcalendar-number-to-kanji 12345678) "千二百三十四万五千六百七十八"))
  (should (equal (jcalendar-number-to-kanji 123456789) "一億二千三百四十五万六千七百八十九"))
  (should (equal (jcalendar-number-to-kanji 2) "二"))
  (should (equal (jcalendar-number-to-kanji 23) "二十三"))
  (should (equal (jcalendar-number-to-kanji 234) "二百三十四"))
  (should (equal (jcalendar-number-to-kanji 2345) "二千三百四十五"))
  (should (equal (jcalendar-number-to-kanji 23456) "二万三千四百五十六"))
  (should (equal (jcalendar-number-to-kanji 234567) "二十三万四千五百六十七"))
  (should (equal (jcalendar-number-to-kanji 2345678) "二百三十四万五千六百七十八"))
  (should (equal (jcalendar-number-to-kanji 23456789) "二千三百四十五万六千七百八十九"))
  (should (equal (jcalendar-number-to-kanji 234567891) "二億三千四百五十六万七千八百九十一"))
  (should (equal (jcalendar-number-to-kanji 123123) "十二万三千百二十三"))
  (should (equal (jcalendar-number-to-kanji 23123) "二万三千百二十三"))
  (should (equal (jcalendar-number-to-kanji 23023) "二万三千二十三"))
  (should (equal (jcalendar-number-to-kanji 230) "二百三十"))
  (should (equal (jcalendar-number-to-kanji 20) "二十")))

(provide 'jcalendar-test)
